## Alertmanager 配置文件
global:
  resolve_timeout: 10s

# 路由分组
route:
  receiver: default-receiver
  group_wait: 10s # 在组内等待所配置的时间，如果同组内，30秒内出现相同报警，在一个组内出现。
  group_interval: 10s # 如果组内内容不变化，合并为一条警报信息，5m后发送。
  repeat_interval: 10s # 发送报警间隔，如果指定时间内没有修复，则重新发送报警。
  routes:
  - receiver: crawl_monitoring
    # group_by: [product, environment]
    match:
      project: crawl_monitoring

receivers:
  - name: default-receiver
    webhook_configs:
      - url: http://alertmanager-webhook-api-server-prod.mediawise.svc.cluster.local:8110/push/default-receiver/
  
  - name: crawl_monitoring
    webhook_configs:
      - url: http://alertmanager-webhook-api-server-prod.mediawise.svc.cluster.local:8110/push/clipresult_parse_result/
