version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/bot/opt/docker-compose-public/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/bot/opt/docker-compose-public/prometheus/rules:/etc/prometheus/rules/

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /home/bot/opt/docker-compose-public/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  elasticsearch_exporter:
    container_name: elasticsearch_exporter
    image: justwatch/elasticsearch_exporter:1.1.0
    command:
      - "--es.uri=http://192.168.31.245:9200"
      - "--es.all"
      - "--es.indices"
      - "--es.cluster_settings"
      - "--es.indices_settings"
      - "--es.shards"
      - "--es.snapshots"
    restart: always
    ports:
      - "9114:9114"

  # mysqld-exporter:
  #   image: prom/mysqld-exporter
  #   container_name: mysqld-exporter
  #   environment:
  #     - DATA_SOURCE_NAME="root:yjcyjc@(192.168.31.245:3306)/"
  #   ports:
  #     - "9093:9093"

  # rabbitmq-exporter:
  #   image: prom/rabbitmq-exporter
  #   container_name: rabbitmq-exporter
  #   environment:
  #     RABBIT_USER: pon
  #     RABBIT_PASSWORD: pon
  #   ports:
  #     - "9093:9093"

  # command:
  #   - "--path.rootfs=/host"
  # network_mode: host
  # pid: host
  # restart: unless-stopped
  # volumes:
  #   - "/:/host:ro,rslave"

  # prometheus-webhook-dingtalk:
  #     container_name: prometheus-webhook-dingtalk
  #     image: timonwong/prometheus-webhook-dingtalk
  #     volumes:
  #         - /home/vobile/opt/monitoring/config.yaml:/etc/prometheus-webhook-dingtalk/config.yml
  #     ports:
  #         - "8060:8060"

  # mysqld-exporter:
  #     container_name: mysqld-exporter
  #     image: prom/mysqld-exporter
  #     environment:
  #         DATA_SOURCE_NAME: root:123456@(192.168.26.174:3306)/
  #     ports:
  #         - "9104:9104"

  # influxdb:
  #     image: influxdb:1.8
  #     ports:
  #     - "8086:8086"

  # pushgateway:
  #     image: prom/pushgateway
  #     ports:
  #     - "9091:9091"
