version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: pon
      MONGO_INITDB_ROOT_PASSWORD: ponponon

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pon
      ME_CONFIG_MONGODB_ADMINPASSWORD: ponponon
      ME_CONFIG_MONGODB_URL: mongodb://pon:ponponon@10.0.4.16:27017/
