version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/:/data/db
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://172.16.21.151:27017/
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"
