version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fastapi_example.conf:/etc/nginx/conf.d/fastapi_example.conf
    ports:
      - 80:80
